### ISSUE TITLE
Crash when using Hotbar Hotkeys

### ISSUE THREAD

**Issue by MxPyx** [FlexibleGames/CraftingTable#1]
Game crashes when Hotbar hotkey is used to "swap in" and then "swap out" to the same hotbar location.

Steps:
With an item in slot 1 and the crafting table crafting menu open,
Place the cursor over the first slot of the crafting table
Press 1 to move the item into the crafting table
Press 1 to move the item out of the crafting table
Crash
[client-main.txt](https://github.com/FlexibleGames/CraftingTable/files/14274948/client-main.txt)
[client-crash.txt](https://github.com/FlexibleGames/CraftingTable/files/14274949/client-crash.txt)

**Comment by FlexibleGames** [comment]
Looking into it now.

**Comment by FlexibleGames** [comment]
So I figured out why it happens, because the ItemSlot in the table loses it's 'highlight' when the move operation is performed when you hit 1 again the slot highlighted is actually the hotbar even though the mouse hasn't moved.

Working to figure out how to keep the highlighted slot in the table now.

**Comment by FlexibleGames** [comment]
Maybe not, I've got it saving the highlight, but the exception is still thrown. This issue goes deeper than I thought

**Comment by MxPyx** [comment]
Awesome! Thanks for taking care of this so quick!!

**Comment by FlexibleGames** [comment]
Took 8 hours to track down, but it was important I know the solution so I didn't spread the bug to other mods.
